/*
 * Заказ ресурсов на облаке
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.User;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * Create user
     *
     * This can only be done by the logged in user.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createUserTest() throws Exception {
        User body = null;
        User response = api.createUser(body);

        // TODO: test validations
    }
    /**
     * Creates list of users with given input array
     *
     * Creates list of users with given input array
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createUsersWithListInputTest() throws Exception {
        List<User> body = null;
        User response = api.createUsersWithListInput(body);

        // TODO: test validations
    }
    /**
     * Delete user
     *
     * This can only be done by the logged in user.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteUserTest() throws Exception {
        String username = null;
        api.deleteUser(username);

        // TODO: test validations
    }
    /**
     * Get user by user name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserByNameTest() throws Exception {
        String username = null;
        User response = api.getUserByName(username);

        // TODO: test validations
    }
    /**
     * Logs user into the system
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void loginUserTest() throws Exception {
        String username = null;
        String password = null;
        String response = api.loginUser(username, password);

        // TODO: test validations
    }
    /**
     * Logs out current logged in user session
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void logoutUserTest() throws Exception {
        api.logoutUser();

        // TODO: test validations
    }
    /**
     * Update user
     *
     * This can only be done by the logged in user.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateUserTest() throws Exception {
        String username = null;
        User body = null;
        api.updateUser(username, body);

        // TODO: test validations
    }
}
